# Texas COVID Vulnerability Report
**by Yvonne King, Brandi Reger, Jada Shipp, and Wenliang Sun**

**Quick Notebook Reference**

1. Project Plan
2. Imports
3. Acquire
4. Prep
5. Exploration
6. Models
7. Model Evaluation
8. Final Conclusions

##Project Plan

**Acquisition, Prep, and Initial Exploration**
- Read in various files
- Handle Missing Values
- Remove/repair erroneous data
- Look at shape of data

**Exploration**
- Answer the following questions:
    - What social features are related to spikes in COVID

**Modeling**
- Time Series Analysis - Using our social vulnerability index we want to create a model to show weekly growth/decline of COVID per county
- We will use classification, time series, and possibly regression to predict case increases

**Main Hypotheses**

- $H_0$: Vulnerability score is not related to higher infection rate.
- $H_a$: Vulnerability score is related to higher infection rate


- $H_0$: Population density correlates to higher infection rate
- $H_a$: Population density does not correlate to higher infection rate 


- $H_0$: Counties with higher population of senior citizens have higher infection rates
- $H_a$: Counties with higher population of senior citizens do not have higher infection rates

## Imports

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd



import acquire
import prepare
import explore

## Acquire
- The ```acquire.py``` file has all the functions to call in our dataframes for the Texas subsets of the following files (which can be found in the Data folder:
    - County Classification
    - Cumulative Tests over Time by County
    - Food1
    - Hospitals
    - Jobs
    - NursinfFacilities
    - People
    - time_series_covid19_confirmed_US
    - Variable Name Lookup
    - Veterans
- We went through all the files above and dropped erroneous columns
- After each file was combed through, we combined all data into one large dataframe using the```merge_dataframes()``` function in the ```acquire.py```

In [2]:
#bring in complete dataframe
df = acquire.merge_dataframes()

#take a peek at the data
df.sample(5)

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,Age65AndOlderNum2010,Under18Num2010,...,FIPS,num_nursing_homes,total_tests,Public Health Region (11),Health Service Region (8),RPL_THEME1,RPL_THEME2,RPL_THEME3,RPL_THEME4,RPL_THEMES
67,28118.394313,ector,60431.0,4.661063,8634.0,20485.0,897.69,162124.0,13954,39808,...,48135,6.0,4208,9,9/10,0.4862,0.4822,0.8498,0.6719,0.6877
162,10912.827726,medina,59304.0,4.570830,2077.0,5988.0,1325.36,50921.0,6210,11865,...,48325,2.0,908,8,8,0.1937,0.3518,0.5138,0.7036,0.4071
138,14616.198773,lamar,45767.0,9.014327,2591.0,7066.0,907.19,49728.0,8276,12095,...,48277,5.0,1293,4,4/5N,0.6443,0.8814,0.1344,0.4980,0.5731
59,377.202792,delta,44410.0,6.719751,318.0,908.0,256.83,5349.0,1037,1185,...,48119,1.0,98,4,4/5N,0.6008,0.6522,0.0435,0.2134,0.2885
121,689.233039,jeff davis,51343.0,2.854512,33.0,284.0,2264.56,2252.0,543,464,...,48243,NaN,10,10,9/10,0.1897,0.1621,0.5059,0.1067,0.1067

In [3]:
#look at the shape of the data
df.shape

(254, 78)

In [4]:
#look at data types and counts
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 254 entries, 0 to 253
Data columns (total 78 columns):
LACCESS_POP15                         253 non-null float64
County                                254 non-null object
MedHHInc                              254 non-null float64
Deep_Pov_All                          254 non-null float64
PovertyUnder18Num                     254 non-null float64
PovertyAllAgesNum                     254 non-null float64
LandAreaSQMiles2010                   254 non-null float64
TotalPopEst2018                       254 non-null float64
Age65AndOlderNum2010                  254 non-null int64
Under18Num2010                        254 non-null int64
NaturalChange1018                     254 non-null float64
AvgHHSize                             254 non-null float64
TotalOccHU                            254 non-null int64
OwnHomeNum                            254 non-null int64
FemaleHHNum                           254 non-null int64
TotalHH                               254 non-null int64
NonEnglishHHNum                       254 non-null int64
HH65PlusAloneNum                      254 non-null int64
Ed1LessThanHSNum                      254 non-null int64
Ed2HSDiplomaOnlyNum                   254 non-null int64
Ed3SomeCollegeNum                     254 non-null int64
Ed4AssocDegreeNum                     254 non-null int64
Ed5CollegePlusNum                     254 non-null int64
WhiteNonHispanicNum2010               254 non-null int64
BlackNonHispanicNum2010               254 non-null int64
AsianNonHispanicNum2010               254 non-null int64
NativeAmericanNonHispanicNum2010      254 non-null int64
HispanicNum2010                       254 non-null int64
MultipleRaceNum2010                   254 non-null int64
State                                 254 non-null object
MedianVetsInc                         246 non-null float64
MedianNonVetsInc                      254 non-null float64
Vets18ONum                            254 non-null float64
CLFVets18to64Num                      254 non-null float64
NonVetsDisabilty                      254 non-null float64
VetsDisabilty                         254 non-null float64
NonVetsPoor                           254 non-null float64
VetsPoor                              254 non-null float64
UnempRate2018                         254 non-null float64
NumCivLaborforce2018                  254 non-null float64
PctEmpAgriculture                     254 non-null float64
PctEmpMining                          254 non-null float64
PctEmpConstruction                    254 non-null float64
PctEmpManufacturing                   254 non-null float64
PctEmpTrade                           254 non-null float64
PctEmpTrans                           254 non-null float64
PctEmpInformation                     254 non-null float64
PctEmpFIRE                            254 non-null float64
PctEmpServices                        254 non-null float64
PctEmpGovt                            254 non-null float64
RuralUrbanContinuumCode2013           254 non-null float64
UrbanInfluenceCode2013                254 non-null float64
Metro2013                             254 non-null float64
Micropolitan2013                      254 non-null float64
Type_2015_Farming_NO                  254 non-null float64
Type_2015_Manufacturing_NO            254 non-null float64
Type_2015_Mining_NO                   254 non-null float64
Type_2015_Government_NO               254 non-null float64
Type_2015_Recreation_NO               254 non-null float64
Low_Employment_2015_update            254 non-null float64
Population_loss_2015_update           254 non-null float64
Retirement_Destination_2015_Update    254 non-null float64
HiAmenity                             254 non-null float64
Metro_Adjacent2013                    254 non-null float64
num_hospitals                         186 non-null float64
population                            254 non-null int64
num_covid_cases                       254 non-null int64
infection_pct                         254 non-null float64
FIPS                                  254 non-null int64
num_nursing_homes                     220 non-null float64
total_tests                           254 non-null int64
Public Health Region (11)             254 non-null int64
Health Service Region (8)             254 non-null object
RPL_THEME1                            254 non-null float64
RPL_THEME2                            254 non-null float64
RPL_THEME3                            254 non-null float64
RPL_THEME4                            254 non-null float64
RPL_THEMES                            254 non-null float64
dtypes: float64(51), int64(24), object(3)
memory usage: 156.8+ KB

# Prepare

During the preparation phase we:
1. Handled any null values by replacing them with zero since each row represents a county in Texas
2. Added the following calculated fields:
    - Cases per 1k, 10k, & 100k
    - Positivity rate (cases / tests)
    - population density (how many people per sq mile of land in the county)
    - numerical columns into percents
    - Proportion of all children that live below poverty line
    - Proportion of population that live below poverty line
    - Proportion of seniors that live below poverty line
    - Percentage of heads of house who own their home
    - Rent home percentage
    - Percentage for female heads of households
    - of all heads of households, what proportion are over 65 and live alone
    - of all heads of households, what proportion do not speak english
    - of the adult population, what proportion have what level of education
    - of the population, what proportion are various races
    - How does the median income for vets compare to the median income in the county
    - What proportion of the adult population is a vet
    - What proportion of the adult population is disabled
    - What proportion of the vet population is poor
3. Capitalized county name
4. Updated all datatypes
5. Rounded decimals to 2 pints
6. Created the following categorical columns:
    - Population density binned into High, Mid and low
    - Infection percent binned into High, Mid and low

Functions have been created to handle all of the above in the ```prepare.py``` file

To bring in the data we will call the ```get_data()``` function from the ```prepare.py``` file

In [5]:
#read in dataframe
df = prepare.get_data()

In [6]:
#take a look at a sample of our data to ensure everything came in as anticipated
df.sample(3)

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,Age65AndOlderNum2010,Under18Num2010,...,asian_pct,nat_am_pct,hispanic_pct,multi_race_pct,med_inc_vet_vs_civ,all_vet_pct,disabled_pct,poor_vets_pct,pop_density_category,infection_pct_category
107,269110.460682,Hidalgo,38785,14.317789,112825,256985,1570,865939,72248,268484,...,0.01,0.00,0.81,0.01,2.00,0.03,0.08,0.05,high,mid
116,6465.426391,Hutchinson,54351,7.200821,1003,2708,887,21198,3266,5828,...,0.00,0.01,0.20,0.03,1.64,0.07,0.14,0.06,mid,mid
4,2147.672378,Archer,61190,3.490241,268,922,903,8786,1447,2185,...,0.00,0.01,0.08,0.02,1.31,0.10,0.10,0.01,mid,low

In [7]:
#Let's take a quick look at the shape of the data to make sure no rows were dropped
df.shape

(254, 110)

**Quick Notes**
- Each row in our dataframe represents a County in Texas
- There are 254 Counties in Texas and those counties are broken into 11 regions across Texas

# Exploratory Data Analysis (EDA)