# Texas COVID Vulnerability Report
**by Yvonne King, Brandi Reger, Jada Shipp, and Wenliang Sun**

**Quick Notebook Reference**

1. Project Plan
2. Imports
3. Acquire
4. Prep
5. Exploration
6. Models
7. Model Evaluation
8. Final Conclusions

##Project Plan

**Acquisition, Prep, and Initial Exploration**
- Read in various files
- Handle Missing Values
- Remove/repair erroneous data
- Look at shape of data

**Exploration**
- Answer the following questions:
    - What social features are related to spikes in COVID

**Modeling**
- Time Series Analysis - Using our social vulnerability index we want to create a model to show weekly growth/decline of COVID per county
- We will use classification, time series, and possibly regression to predict case increases

**Main Hypotheses**

- $H_0$: Vulnerability score is not related to higher infection rate.
- $H_a$: Vulnerability score is related to higher infection rate


- $H_0$: Population density correlates to higher infection rate
- $H_a$: Population density does not correlate to higher infection rate 


- $H_0$: Counties with higher population of senior citizens have higher infection rates
- $H_a$: Counties with higher population of senior citizens do not have higher infection rates

## Imports

In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas

import acquire
import prepare
import explore

## Acquire
- The ```acquire.py``` file has all the functions to call in our dataframes for the Texas subsets of the following files (which can be found in the Data folder:
    - County Classification
    - Cumulative Tests over Time by County
    - Food1
    - Hospitals
    - Jobs
    - NursinfFacilities
    - People
    - time_series_covid19_confirmed_US
    - Variable Name Lookup
    - Veterans
- We went through all the files above and dropped erroneous columns
- After each file was combed through, we combined all data into one large dataframe using the```merge_dataframes()``` function in the ```acquire.py```

In [2]:
#bring in complete dataframe
df = acquire.merge_dataframes()

#take a peek at the data
df.sample(5)

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,...,Retirement_Destination_2015_Update,HiAmenity,Metro_Adjacent2013,num_hospitals,population,num_covid_cases,infection_pct,FIPS,num_nursing_homes,total_tests
17,1762.381976,bosque,48460.0,4.577823,954.0,2721.0,982.98,18691.0,18.53,3844,...,1.0,0.0,1.0,1.0,17765,10,0.056290,48035,4.0,941
153,2707.340170,mcculloch,42719.0,6.089499,486.0,1449.0,1065.60,7987.0,7.77,1645,...,0.0,1.0,0.0,1.0,8660,5,0.057737,48307,1.0,83
225,44739.347357,tom green,51393.0,5.189524,6605.0,17558.0,1521.97,118189.0,72.42,15265,...,0.0,1.0,0.0,4.0,123276,186,0.150881,48451,7.0,2441
118,4294.148336,jack,48780.0,8.396349,415.0,1359.0,910.66,8843.0,9.93,1350,...,0.0,0.0,1.0,1.0,8841,4,0.045244,48237,1.0,100
140,4014.559548,lampasas,55151.0,5.303179,928.0,2713.0,712.84,21229.0,27.60,3101,...,1.0,1.0,0.0,1.0,21037,17,0.080810,48281,3.0,1396

In [3]:
#look at the shape of the data
df.shape

(254, 74)

In [4]:
#look at data types and counts
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 254 entries, 0 to 253
Data columns (total 74 columns):
LACCESS_POP15                         253 non-null float64
County                                254 non-null object
MedHHInc                              254 non-null float64
Deep_Pov_All                          254 non-null float64
PovertyUnder18Num                     254 non-null float64
PovertyAllAgesNum                     254 non-null float64
LandAreaSQMiles2010                   254 non-null float64
TotalPopEst2018                       254 non-null float64
PopDensity2010                        254 non-null float64
Age65AndOlderNum2010                  254 non-null int64
Under18Num2010                        254 non-null int64
NaturalChange1018                     254 non-null float64
AvgHHSize                             254 non-null float64
TotalOccHU                            254 non-null int64
OwnHomeNum                            254 non-null int64
FemaleHHNum                           254 non-null int64
TotalHH                               254 non-null int64
NonEnglishHHNum                       254 non-null int64
HH65PlusAloneNum                      254 non-null int64
Ed1LessThanHSNum                      254 non-null int64
Ed2HSDiplomaOnlyNum                   254 non-null int64
Ed3SomeCollegeNum                     254 non-null int64
Ed4AssocDegreeNum                     254 non-null int64
Ed5CollegePlusNum                     254 non-null int64
WhiteNonHispanicNum2010               254 non-null int64
BlackNonHispanicNum2010               254 non-null int64
AsianNonHispanicNum2010               254 non-null int64
NativeAmericanNonHispanicNum2010      254 non-null int64
HispanicNum2010                       254 non-null int64
MultipleRaceNum2010                   254 non-null int64
State                                 254 non-null object
MedianVetsInc                         246 non-null float64
MedianNonVetsInc                      254 non-null float64
Vets18ONum                            254 non-null float64
CLFVets18to64Num                      254 non-null float64
NonVetsDisabilty                      254 non-null float64
VetsDisabilty                         254 non-null float64
NonVetsPoor                           254 non-null float64
VetsPoor                              254 non-null float64
UnempRate2018                         254 non-null float64
NumUnemployed2018                     254 non-null float64
NumEmployed2018                       254 non-null float64
NumCivLaborforce2018                  254 non-null float64
PctEmpAgriculture                     254 non-null float64
PctEmpMining                          254 non-null float64
PctEmpConstruction                    254 non-null float64
PctEmpManufacturing                   254 non-null float64
PctEmpTrade                           254 non-null float64
PctEmpTrans                           254 non-null float64
PctEmpInformation                     254 non-null float64
PctEmpFIRE                            254 non-null float64
PctEmpServices                        254 non-null float64
PctEmpGovt                            254 non-null float64
RuralUrbanContinuumCode2013           254 non-null float64
UrbanInfluenceCode2013                254 non-null float64
Metro2013                             254 non-null float64
Micropolitan2013                      254 non-null float64
Type_2015_Farming_NO                  254 non-null float64
Type_2015_Manufacturing_NO            254 non-null float64
Type_2015_Mining_NO                   254 non-null float64
Type_2015_Government_NO               254 non-null float64
Type_2015_Recreation_NO               254 non-null float64
Low_Employment_2015_update            254 non-null float64
Population_loss_2015_update           254 non-null float64
Retirement_Destination_2015_Update    254 non-null float64
HiAmenity                             254 non-null float64
Metro_Adjacent2013                    254 non-null float64
num_hospitals                         186 non-null float64
population                            254 non-null int64
num_covid_cases                       254 non-null int64
infection_pct                         254 non-null float64
FIPS                                  254 non-null int64
num_nursing_homes                     220 non-null float64
total_tests                           254 non-null int64
dtypes: float64(49), int64(23), object(2)
memory usage: 148.8+ KB

# Prepare

In [5]:
df = prepare.prep_dataframe(df)
df.sample(5)

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,...,asian_pct,nat_am_pct,hispanic_pct,multi_race_pct,med_inc_vet_vs_civ,all_vet_pct,disabled_pct,poor_vets_pct,pop_density_category,infection_pct_category
20,52558.408686,Brazos,50113.0,15.102377,9297.0,49310.0,585.45,226758.0,332.83,14059,...,4.351162,0.210976,19.792075,1.987272,191.173692,4.406079,4.965740,6.141506,high,high
16,641.000000,Borden,66101.0,1.057402,19.0,65.0,897.44,648.0,0.71,133,...,0.145985,0.291971,13.868613,1.459854,69.951554,7.312614,8.957952,0.000000,low,low
79,743.871196,Franklin,48222.0,4.284498,599.0,1615.0,284.39,10766.0,37.29,1981,...,0.448554,0.595020,12.202490,1.739290,185.832128,10.898822,9.901466,3.969129,mid,mid
248,3519.045576,Wise,66387.0,4.767079,2344.0,6643.0,904.42,68305.0,65.38,7279,...,0.355585,0.518182,15.366146,1.881259,141.420680,9.765098,11.661773,5.160504,high,mid
26,14182.998882,Burnet,56696.0,3.340408,1872.0,5099.0,994.26,47542.0,43.00,7945,...,0.410822,0.350652,17.951697,1.647440,144.218643,10.024820,9.964729,6.046390,mid,mid