In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv('../Data/People.csv')

In [2]:
df.head()

,FIPS,State,County,PopChangeRate1718,PopChangeRate1018,TotalPopEst2018,NetMigrationRate1018,NaturalChangeRate1018,Net_International_Migration_Rate_2010_2018,PopChangeRate0010,...,TotalPopEst2010,TotalPopEst2014,TotalPopEst2011,Net_International_Migration_2010_2018,NaturalChange1018,TotalPopEst2015,TotalPopEst2016,TotalPopEst2017,NetMigration1018,TotalPopEstBase2010
0,0,US,United States,0.72,5.30,NaN,2.28,3.02,2.28,9.71,...,309338421,318622525,311644280,7042455.0,9338302.0,321039839,323405935,325719178,7042455.0,308758105
1,1000,AL,Alabama,0.26,2.14,4887871.0,0.84,1.30,0.77,7.48,...,4785448,4842481,4798834,36623.0,62441.0,4853160,4864745,4875120,39982.0,4780138
2,1001,AL,Autauga,0.28,1.55,55601.0,0.28,1.26,0.06,24.96,...,54754,54876,55208,32.0,692.0,54838,55242,55443,155.0,54574
3,1003,AL,Baldwin,2.54,19.07,218022.0,18.14,0.93,0.74,29.80,...,183111,199189,186540,1364.0,1697.0,202995,207712,212619,33214.0,182264
4,1005,AL,Barbour,-1.10,-8.96,24881.0,-8.27,-0.69,0.14,-5.44,...,27330,26758,27350,38.0,-188.0,26294,25819,25158,-2261.0,27457

In [3]:
df = df[df.State == 'TX']

In [4]:
# Drop columns we don't need 
good_columns = [
    'FIPS', 'State', 'County', 'LandAreaSQMiles2010',
    # Population estimates
    'TotalPopEst2018', 'PopDensity2010', 'Age65AndOlderNum2010', 'Under18Num2010', 'NaturalChange1018',
    # Household size
    'AvgHHSize', 'TotalOccHU', 'OwnHomeNum', 
    # Head of Household
    'FemaleHHNum', 'TotalHH', 
    'NonEnglishHHNum', 'HH65PlusAloneNum',
    # Education columns
    'Ed1LessThanHSNum', 'Ed2HSDiplomaOnlyNum', 'Ed3SomeCollegeNum',
    'Ed4AssocDegreeNum', 'Ed5CollegePlusNum',
    # Race columns
    'WhiteNonHispanicNum2010', 'BlackNonHispanicNum2010',
    'AsianNonHispanicNum2010', 'NativeAmericanNonHispanicNum2010',
    'HispanicNum2010', 'MultipleRaceNum2010'
]

columns_to_drop = [
    'TotalPop2010', 
    'TotalPopEst2012',
    'TotalPopEst2013',
    'TotalPopEst2010',
    'TotalPopEst2014',
    'TotalPopEst2011',
    'TotalPopEst2015', 
    'TotalPopEst2016',
    'TotalPopEst2017', 
    'Net_International_Migration_2000_2010',
    'TotalPopEstBase2010'
    'NetMigrationNum0010',
    'NaturalChangeNum0010',
    'TotalPopACS',
    'TotalPop25Plus',
    'PopChangeRate1718',
    'PopChangeRate1018',
    'NetMigrationRate1018',
    'NaturalChangeRate1018',
    'Net_International_Migration_Rate_2010_2018',
    'PopChangeRate0010',
    'NetMigrationRate0010',
    'NaturalChangeRate0010',
    'Immigration_Rate_2000_2010',
    'NonHispanicWhitePopChangeRate0010',
    'NonHispanicBlackPopChangeRate0010', 
    'NonHispanicAsianPopChangeRate0010',
    'NonHispanicNativeAmericanPopChangeRate0010', 
    'HispanicPopChangeRate0010',
    'MultipleRacePopChangeRate0010',
    'Under18Pct2010',
    'Age65AndOlderPct2010', 
    'WhiteNonHispanicPct2010',
    'BlackNonHispanicPct2010',
    'AsianNonHispanicPct2010', 
    'NativeAmericanNonHispanicPct2010',
    'HispanicPct2010',
    'MultipleRacePct2010',
    'ForeignBornPct',
    'ForeignBornEuropePct', 
    'ForeignBornMexPct',
    'NonEnglishHHPct',
    'Ed1LessThanHSPct',
    'Ed2HSDiplomaOnlyPct',
    'Ed3SomeCollegePct',
    'Ed4AssocDegreePct', 
    'Ed5CollegePlusPct',
    'FemaleHHPct',
    'HH65PlusAlonePct',
    'OwnHomePct', 
    'ForeignBornAfricaPct', 
    'ForeignBornAsiaPct', 
    'ForeignBornCentralSouthAmPct', 
    'ForeignBornCaribPct', 
    'ForeignBornNum',
    'ForeignBornCentralSouthAmNum',
    'ForeignBornCaribNum',
    'ForeignBornAfricaNum',
    'ForeignBornAsiaNum',
    'ForeignBornMexNum',
    'ForeignBornEuropeNum', 
    'Net_International_Migration_2010_2018',
    'NetMigration1018'
]



df = df[good_columns]

In [6]:
# Set index to FIPS
df = df.set_index('FIPS')
df.head()

,State,County,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,Under18Num2010,NaturalChange1018,AvgHHSize,TotalOccHU,...,Ed2HSDiplomaOnlyNum,Ed3SomeCollegeNum,Ed4AssocDegreeNum,Ed5CollegePlusNum,WhiteNonHispanicNum2010,BlackNonHispanicNum2010,AsianNonHispanicNum2010,NativeAmericanNonHispanicNum2010,HispanicNum2010,MultipleRaceNum2010
FIPS,,,,,,,,,,,,,,,,,,,,,
48000,TX,Texas,261231.71,28701845.0,96.26,2601886,6865824,1658238.0,2.86,9553046,...,4448881,3892527,1261050,5219469,11397345,2886825,948426,80586,9460921,679001
48001,TX,Anderson,1062.60,58057.0,55.01,7338,11475,-495.0,2.69,16459,...,15224,10696,2807,4931,35792,12222,283,192,9287,993
48003,TX,Andrews,1500.71,18128.0,9.85,1663,4312,1408.0,3.22,5508,...,3898,2161,753,1103,7083,199,85,95,7195,292
48005,TX,Angelina,797.78,87092.0,108.77,11843,23206,2539.0,2.75,30783,...,18265,14230,4578,9344,54889,12840,744,255,17145,1524
48007,TX,Aransas,252.07,23792.0,91.87,5602,4523,-760.0,2.58,9432,...,5392,4764,1302,3936,16350,258,443,118,5690,523

In [ ]:
# Make a function to do this in one step
def acquire_people_data():
    df = pd.read_csv('../Data/People.csv')
    # Restrict df to only Texas
    df = df[df.State == 'TX']
    # Keep only the columns we want and set index to FIPS
    good_columns = ['FIPS', 'State', 'County', 'LandAreaSQMiles2010',
                    # Population estimates
                    'TotalPopEst2018', 'PopDensity2010', 'Age65AndOlderNum2010',
                    'Under18Num2010', 'NaturalChange1018',
                    # Household size
                    'AvgHHSize', 'TotalOccHU', 'OwnHomeNum', 
                    # Head of Household
                    'FemaleHHNum', 'TotalHH', 'NonEnglishHHNum', 'HH65PlusAloneNum',
                    # Education columns
                    'Ed1LessThanHSNum', 'Ed2HSDiplomaOnlyNum', 'Ed3SomeCollegeNum',
                    'Ed4AssocDegreeNum', 'Ed5CollegePlusNum',
                    # Race columns
                    'WhiteNonHispanicNum2010', 'BlackNonHispanicNum2010',
                    'AsianNonHispanicNum2010', 'NativeAmericanNonHispanicNum2010',
                    'HispanicNum2010', 'MultipleRaceNum2010'
                   ]
    df = df[good_columns].set_index('FIPS')
    return df