# What features do counties with highest infection rates have in common?

In [1]:
import pandas as pd

import acquire

In [2]:
df = acquire.merge_dataframes()
df.head()

/usr/local/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4133: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,...,Population_loss_2015_update,Retirement_Destination_2015_Update,HiAmenity,Metro_Adjacent2013,num_hospitals,population,num_covid_cases,infection_pct,FIPS,num_nursing_homes
0,23111.241421,anderson,45969.0,4.287712,2486.0,8778.0,1062.60,58057.0,55.01,7338,...,0.0,0.0,0.0,0.0,2.0,58199.0,1003.0,1.723397,48001,5.0
1,5015.975463,andrews,84946.0,3.720851,774.0,1922.0,1500.71,18128.0,9.85,1663,...,0.0,0.0,0.0,1.0,1.0,22269.0,33.0,0.148188,48003,1.0
2,20927.331551,angelina,46653.0,7.613627,5855.0,15052.0,797.78,87092.0,108.77,11843,...,0.0,0.0,1.0,0.0,4.0,90437.0,352.0,0.389221,48005,8.0
3,8865.511478,aransas,46912.0,9.002793,1423.0,4642.0,252.07,23792.0,91.87,5602,...,0.0,1.0,1.0,0.0,NaN,27699.0,7.0,0.025272,48007,2.0
4,2147.672378,archer,61190.0,3.490241,268.0,922.0,903.11,8786.0,10.03,1447,...,0.0,0.0,0.0,0.0,NaN,8344.0,3.0,0.035954,48009,1.0

In [3]:
df.columns.to_list()

['LACCESS_POP15',
 'County',
 'MedHHInc',
 'Deep_Pov_All',
 'PovertyUnder18Num',
 'PovertyAllAgesNum',
 'LandAreaSQMiles2010',
 'TotalPopEst2018',
 'PopDensity2010',
 'Age65AndOlderNum2010',
 'Under18Num2010',
 'NaturalChange1018',
 'AvgHHSize',
 'TotalOccHU',
 'OwnHomeNum',
 'FemaleHHNum',
 'TotalHH',
 'NonEnglishHHNum',
 'HH65PlusAloneNum',
 'Ed1LessThanHSNum',
 'Ed2HSDiplomaOnlyNum',
 'Ed3SomeCollegeNum',
 'Ed4AssocDegreeNum',
 'Ed5CollegePlusNum',
 'WhiteNonHispanicNum2010',
 'BlackNonHispanicNum2010',
 'AsianNonHispanicNum2010',
 'NativeAmericanNonHispanicNum2010',
 'HispanicNum2010',
 'MultipleRaceNum2010',
 'State',
 'MedianVetsInc',
 'MedianNonVetsInc',
 'Vets18ONum',
 'CLFVets18to64Num',
 'NonVetsDisabilty',
 'VetsDisabilty',
 'NonVetsPoor',
 'VetsPoor',
 'UnempRate2018',
 'NumUnemployed2018',
 'NumEmployed2018',
 'NumCivLaborforce2018',
 'PctEmpAgriculture',
 'PctEmpMining',
 'PctEmpConstruction',
 'PctEmpManufacturing',
 'PctEmpTrade',
 'PctEmpTrans',
 'PctEmpInformation',
 'PctEmpFIRE',
 'PctEmpServices',
 'PctEmpGovt',
 'RuralUrbanContinuumCode2013',
 'UrbanInfluenceCode2013',
 'Metro2013',
 'Micropolitan2013',
 'Type_2015_Farming_NO',
 'Type_2015_Manufacturing_NO',
 'Type_2015_Mining_NO',
 'Type_2015_Government_NO',
 'Type_2015_Recreation_NO',
 'Low_Employment_2015_update',
 'Population_loss_2015_update',
 'Retirement_Destination_2015_Update',
 'HiAmenity',
 'Metro_Adjacent2013',
 'num_hospitals',
 'population',
 'num_covid_cases',
 'infection_pct',
 'FIPS',
 'num_nursing_homes']