In [1]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

import yk_acquire
import acquire
import prepare

In [2]:
df = yk_acquire.merge_dataframes()

In [3]:
df

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,...,Retirement_Destination_2015_Update,HiAmenity,Metro_Adjacent2013,num_hospitals,population,num_covid_cases,infection_pct,FIPS,num_nursing_homes,total_tests
0,23111.241421,anderson,45969.0,4.287712,2486.0,8778.0,1062.60,58057.0,55.01,7338,...,0.0,0.0,0.0,2.0,58199,1003,1.723397,48001,5.0,2679
1,5015.975463,andrews,84946.0,3.720851,774.0,1922.0,1500.71,18128.0,9.85,1663,...,0.0,0.0,1.0,1.0,22269,33,0.148188,48003,1.0,72
2,20927.331551,angelina,46653.0,7.613627,5855.0,15052.0,797.78,87092.0,108.77,11843,...,0.0,1.0,0.0,4.0,90437,352,0.389221,48005,8.0,3002
3,8865.511478,aransas,46912.0,9.002793,1423.0,4642.0,252.07,23792.0,91.87,5602,...,1.0,1.0,0.0,NaN,27699,7,0.025272,48007,2.0,317
4,2147.672378,archer,61190.0,3.490241,268.0,922.0,903.11,8786.0,10.03,1447,...,0.0,0.0,0.0,NaN,8344,3,0.035954,48009,1.0,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,3222.188853,wood,48384.0,6.128292,2116.0,6625.0,645.23,45129.0,65.04,10148,...,1.0,1.0,1.0,2.0,45292,66,0.145721,48499,5.0,769
250,1562.352965,yoakum,61560.0,5.705285,454.0,1028.0,799.71,8591.0,9.85,895,...,0.0,0.0,0.0,1.0,9225,11,0.119241,48501,1.0,183
251,6142.001383,young,49301.0,5.501855,873.0,2468.0,914.47,18045.0,20.29,3422,...,0.0,0.0,0.0,2.0,18712,15,0.080162,48503,3.0,708
252,6065.681176,zapata,33160.0,18.348365,2297.0,4529.0,998.41,14190.0,14.04,1460,...,0.0,1.0,1.0,NaN,14409,31,0.215143,48505,1.0,421
253,3702.027063,zavala,30076.0,15.852535,1549.0,3701.0,1297.41,11983.0,9.00,1408,...,0.0,0.0,0.0,NaN,12682,13,0.102507,48507,NaN,110

In [4]:
#fill hospital nan with 0
df.num_hospitals = df.num_hospitals.fillna(0)

In [5]:
#fill nursing home nan with 0
df.num_nursing_homes = df.num_nursing_homes.fillna(0)

In [6]:
def fill_nulls_with_zero(dataframe, col_name_string):
    """
    Takes in a dataframe and column name (string) and 
    fills the nan in the specified column with 0
    """
    return dataframe[col_name_string].fillna(0)

In [7]:
df = yk_acquire.merge_dataframes()

In [8]:
df.num_nursing_homes = fill_nulls_with_zero(df, "num_nursing_homes")

In [9]:
df.num_hospitals = fill_nulls_with_zero(df, "num_hospitals")

In [10]:
df.isnull().sum()

LACCESS_POP15        1
County               0
MedHHInc             0
Deep_Pov_All         0
PovertyUnder18Num    0
                    ..
num_covid_cases      0
infection_pct        0
FIPS                 0
num_nursing_homes    0
total_tests          0
Length: 74, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 254 entries, 0 to 253
Data columns (total 74 columns):
LACCESS_POP15                         253 non-null float64
County                                254 non-null object
MedHHInc                              254 non-null float64
Deep_Pov_All                          254 non-null float64
PovertyUnder18Num                     254 non-null float64
PovertyAllAgesNum                     254 non-null float64
LandAreaSQMiles2010                   254 non-null float64
TotalPopEst2018                       254 non-null float64
PopDensity2010                        254 non-null float64
Age65AndOlderNum2010                  254 non-null int64
Under18Num2010                        254 non-null int64
NaturalChange1018                     254 non-null float64
AvgHHSize                             254 non-null float64
TotalOccHU                            254 non-null int64
OwnHomeNum                            254 non-null int64
FemaleHHNum                           254 non-null int64
TotalHH                               254 non-null int64
NonEnglishHHNum                       254 non-null int64
HH65PlusAloneNum                      254 non-null int64
Ed1LessThanHSNum                      254 non-null int64
Ed2HSDiplomaOnlyNum                   254 non-null int64
Ed3SomeCollegeNum                     254 non-null int64
Ed4AssocDegreeNum                     254 non-null int64
Ed5CollegePlusNum                     254 non-null int64
WhiteNonHispanicNum2010               254 non-null int64
BlackNonHispanicNum2010               254 non-null int64
AsianNonHispanicNum2010               254 non-null int64
NativeAmericanNonHispanicNum2010      254 non-null int64
HispanicNum2010                       254 non-null int64
MultipleRaceNum2010                   254 non-null int64
State                                 254 non-null object
MedianVetsInc                         246 non-null float64
MedianNonVetsInc                      254 non-null float64
Vets18ONum                            254 non-null float64
CLFVets18to64Num                      254 non-null float64
NonVetsDisabilty                      254 non-null float64
VetsDisabilty                         254 non-null float64
NonVetsPoor                           254 non-null float64
VetsPoor                              254 non-null float64
UnempRate2018                         254 non-null float64
NumUnemployed2018                     254 non-null float64
NumEmployed2018                       254 non-null float64
NumCivLaborforce2018                  254 non-null float64
PctEmpAgriculture                     254 non-null float64
PctEmpMining                          254 non-null float64
PctEmpConstruction                    254 non-null float64
PctEmpManufacturing                   254 non-null float64
PctEmpTrade                           254 non-null float64
PctEmpTrans                           254 non-null float64
PctEmpInformation                     254 non-null float64
PctEmpFIRE                            254 non-null float64
PctEmpServices                        254 non-null float64
PctEmpGovt                            254 non-null float64
RuralUrbanContinuumCode2013           254 non-null float64
UrbanInfluenceCode2013                254 non-null float64
Metro2013                             254 non-null float64
Micropolitan2013                      254 non-null float64
Type_2015_Farming_NO                  254 non-null float64
Type_2015_Manufacturing_NO            254 non-null float64
Type_2015_Mining_NO                   254 non-null float64
Type_2015_Government_NO               254 non-null float64
Type_2015_Recreation_NO               254 non-null float64
Low_Employment_2015_update            254 non-null float64
Population_loss_2015_update           254 non-null float64
Retirement_Destination_2015_Update    254 non-null float64
HiAmenity                             254 non-null float64
Metro_Adjacent2013                    254 non-null float64
num_hospitals                         254 non-null float64
population                            254 non-null int64
num_covid_cases                       254 non-null int64
infection_pct                         254 non-null float64
FIPS                                  254 non-null int64
num_nursing_homes                     254 non-null float64
total_tests                           254 non-null int64
dtypes: float64(49), int64(23), object(2)
memory usage: 148.8+ KB

***Need to look at LACCESS_POP15 it has one null and MedianVetsInc has 8 nulls***

In [12]:
df.LACCESS_POP15.median()

3836.05728111802

In [13]:
df.LACCESS_POP15.mean()

22636.085931470443

In [14]:
df.LACCESS_POP15.min()

0.0

In [15]:
df.LACCESS_POP15.max()

740267.412660948

In [16]:
df.LACCESS_POP15.nunique()

253

In [17]:
pd.set_option('display.max_columns', None)

In [18]:
df[df['MedianVetsInc'].isna()]

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,Under18Num2010,NaturalChange1018,AvgHHSize,TotalOccHU,OwnHomeNum,FemaleHHNum,TotalHH,NonEnglishHHNum,HH65PlusAloneNum,Ed1LessThanHSNum,Ed2HSDiplomaOnlyNum,Ed3SomeCollegeNum,Ed4AssocDegreeNum,Ed5CollegePlusNum,WhiteNonHispanicNum2010,BlackNonHispanicNum2010,AsianNonHispanicNum2010,NativeAmericanNonHispanicNum2010,HispanicNum2010,MultipleRaceNum2010,State,MedianVetsInc,MedianNonVetsInc,Vets18ONum,CLFVets18to64Num,NonVetsDisabilty,VetsDisabilty,NonVetsPoor,VetsPoor,UnempRate2018,NumUnemployed2018,NumEmployed2018,NumCivLaborforce2018,PctEmpAgriculture,PctEmpMining,PctEmpConstruction,PctEmpManufacturing,PctEmpTrade,PctEmpTrans,PctEmpInformation,PctEmpFIRE,PctEmpServices,PctEmpGovt,RuralUrbanContinuumCode2013,UrbanInfluenceCode2013,Metro2013,Micropolitan2013,Type_2015_Farming_NO,Type_2015_Manufacturing_NO,Type_2015_Mining_NO,Type_2015_Government_NO,Type_2015_Recreation_NO,Low_Employment_2015_update,Population_loss_2015_update,Retirement_Destination_2015_Update,HiAmenity,Metro_Adjacent2013,num_hospitals,population,num_covid_cases,infection_pct,FIPS,num_nursing_homes,total_tests
130,404.209140,kenedy,42153.0,3.697479,24.0,63.0,1458.33,442.0,0.29,59,102,15.0,2.82,209,71,59,209,92,26,274,87,17,7,28,86,1,1,6,319,12,TX,NaN,22804.0,0.0,0.0,36.0,0.0,12.0,0.0,3.7,9.0,233.0,242.0,30.000000,0.000000,5.000000,5.000000,13.636364,7.727273,0.000000,0.000000,20.454545,18.181818,9.0,8.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,476,0,0.000000,48261,0.0,2
131,785.337693,kent,47625.0,1.131542,28.0,89.0,902.51,726.0,0.90,208,185,-41.0,2.22,318,223,23,318,3,71,104,182,117,22,131,669,6,0,5,120,11,TX,NaN,30000.0,41.0,7.0,93.0,0.0,19.0,0.0,2.4,11.0,447.0,458.0,6.472492,5.825243,5.177994,4.854369,15.533981,1.294498,0.647249,8.414239,36.569579,15.210356,9.0,10.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,795,0,0.000000,48263,1.0,3
134,285.999999,king,57925.0,8.771930,11.0,38.0,910.87,277.0,0.31,38,68,9.0,2.51,91,34,11,91,2,15,23,60,39,8,29,242,0,0,1,39,4,TX,NaN,37941.0,7.0,3.0,12.0,0.0,8.0,0.0,2.8,6.0,208.0,214.0,33.606557,6.557377,7.377049,2.459016,4.098361,4.098361,1.639344,1.639344,27.868852,10.655738,9.0,12.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,309,0,0.000000,48269,0.0,3
135,154.874240,kinney,43192.0,8.321210,188.0,724.0,1360.05,3767.0,2.65,874,724,1.0,2.94,1170,868,78,1170,38,316,731,979,655,117,265,1496,39,10,19,2004,74,TX,NaN,17512.0,682.0,497.0,192.0,198.0,311.0,51.0,4.7,59.0,1198.0,1257.0,2.555647,1.813685,9.975268,0.577082,3.874691,13.932399,0.000000,3.215169,34.872218,29.183842,7.0,10.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,3462,1,0.028885,48271,0.0,19
141,3980.727582,la salle,40072.0,5.671457,509.0,1737.0,1486.69,7531.0,4.63,857,1494,322.0,2.92,2216,1515,242,2216,384,428,1606,2150,522,117,664,894,18,6,25,5920,80,TX,NaN,21424.0,165.0,138.0,565.0,26.0,310.0,20.0,2.4,112.0,4487.0,4599.0,15.237420,9.922041,3.401843,4.464918,8.788094,8.504607,0.000000,2.055280,41.105599,6.520198,6.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,8309,5,0.060176,48283,1.0,487
150,82.000000,loving,78637.0,0.000000,5.0,5.0,668.93,152.0,0.12,12,9,7.0,3.09,33,21,0,33,3,6,17,15,29,14,0,60,0,0,4,18,6,TX,NaN,22500.0,3.0,0.0,11.0,0.0,0.0,0.0,3.9,4.0,98.0,102.0,8.333333,27.777778,0.000000,0.000000,38.888889,0.000000,0.000000,16.666667,8.333333,0.000000,9.0,12.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,92,0,0.000000,48301,0.0,1
191,214.356282,reagan,65273.0,7.508073,146.0,371.0,1175.30,3741.0,2.86,349,1010,286.0,3.24,1147,801,103,1147,152,66,462,878,618,83,242,1219,65,1,7,2051,62,TX,NaN,36738.0,124.0,69.0,128.0,7.0,294.0,0.0,2.5,47.0,1849.0,1896.0,2.789318,44.035608,1.364985,1.008902,6.646884,13.353116,0.000000,2.314540,26.528190,1.958457,6.0,6.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,4226,2,0.047326,48383,1.0,99
196,843.189122,roberts,67470.0,4.613610,22.0,70.0,924.06,903.0,1.01,149,236,9.0,2.85,311,232,26,311,0,25,51,157,162,48,149,841,0,2,3,74,19,TX,NaN,33571.0,47.0,27.0,30.0,18.0,18.0,18.0,3.0,13.0,423.0,436.0,17.711172,6.267030,10.899183,8.719346,13.896458,5.449591,0.544959,2.179837,30.517711,3.814714,9.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,983,2,0.203459,48393,0.0,6

In [19]:
df = df.fillna(0)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 254 entries, 0 to 253
Data columns (total 74 columns):
LACCESS_POP15                         254 non-null float64
County                                254 non-null object
MedHHInc                              254 non-null float64
Deep_Pov_All                          254 non-null float64
PovertyUnder18Num                     254 non-null float64
PovertyAllAgesNum                     254 non-null float64
LandAreaSQMiles2010                   254 non-null float64
TotalPopEst2018                       254 non-null float64
PopDensity2010                        254 non-null float64
Age65AndOlderNum2010                  254 non-null int64
Under18Num2010                        254 non-null int64
NaturalChange1018                     254 non-null float64
AvgHHSize                             254 non-null float64
TotalOccHU                            254 non-null int64
OwnHomeNum                            254 non-null int64
FemaleHHNum                           254 non-null int64
TotalHH                               254 non-null int64
NonEnglishHHNum                       254 non-null int64
HH65PlusAloneNum                      254 non-null int64
Ed1LessThanHSNum                      254 non-null int64
Ed2HSDiplomaOnlyNum                   254 non-null int64
Ed3SomeCollegeNum                     254 non-null int64
Ed4AssocDegreeNum                     254 non-null int64
Ed5CollegePlusNum                     254 non-null int64
WhiteNonHispanicNum2010               254 non-null int64
BlackNonHispanicNum2010               254 non-null int64
AsianNonHispanicNum2010               254 non-null int64
NativeAmericanNonHispanicNum2010      254 non-null int64
HispanicNum2010                       254 non-null int64
MultipleRaceNum2010                   254 non-null int64
State                                 254 non-null object
MedianVetsInc                         254 non-null float64
MedianNonVetsInc                      254 non-null float64
Vets18ONum                            254 non-null float64
CLFVets18to64Num                      254 non-null float64
NonVetsDisabilty                      254 non-null float64
VetsDisabilty                         254 non-null float64
NonVetsPoor                           254 non-null float64
VetsPoor                              254 non-null float64
UnempRate2018                         254 non-null float64
NumUnemployed2018                     254 non-null float64
NumEmployed2018                       254 non-null float64
NumCivLaborforce2018                  254 non-null float64
PctEmpAgriculture                     254 non-null float64
PctEmpMining                          254 non-null float64
PctEmpConstruction                    254 non-null float64
PctEmpManufacturing                   254 non-null float64
PctEmpTrade                           254 non-null float64
PctEmpTrans                           254 non-null float64
PctEmpInformation                     254 non-null float64
PctEmpFIRE                            254 non-null float64
PctEmpServices                        254 non-null float64
PctEmpGovt                            254 non-null float64
RuralUrbanContinuumCode2013           254 non-null float64
UrbanInfluenceCode2013                254 non-null float64
Metro2013                             254 non-null float64
Micropolitan2013                      254 non-null float64
Type_2015_Farming_NO                  254 non-null float64
Type_2015_Manufacturing_NO            254 non-null float64
Type_2015_Mining_NO                   254 non-null float64
Type_2015_Government_NO               254 non-null float64
Type_2015_Recreation_NO               254 non-null float64
Low_Employment_2015_update            254 non-null float64
Population_loss_2015_update           254 non-null float64
Retirement_Destination_2015_Update    254 non-null float64
HiAmenity                             254 non-null float64
Metro_Adjacent2013                    254 non-null float64
num_hospitals                         254 non-null float64
population                            254 non-null int64
num_covid_cases                       254 non-null int64
infection_pct                         254 non-null float64
FIPS                                  254 non-null int64
num_nursing_homes                     254 non-null float64
total_tests                           254 non-null int64
dtypes: float64(49), int64(23), object(2)
memory usage: 148.8+ KB

In [21]:
df.head()

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,Under18Num2010,NaturalChange1018,AvgHHSize,TotalOccHU,OwnHomeNum,FemaleHHNum,TotalHH,NonEnglishHHNum,HH65PlusAloneNum,Ed1LessThanHSNum,Ed2HSDiplomaOnlyNum,Ed3SomeCollegeNum,Ed4AssocDegreeNum,Ed5CollegePlusNum,WhiteNonHispanicNum2010,BlackNonHispanicNum2010,AsianNonHispanicNum2010,NativeAmericanNonHispanicNum2010,HispanicNum2010,MultipleRaceNum2010,State,MedianVetsInc,MedianNonVetsInc,Vets18ONum,CLFVets18to64Num,NonVetsDisabilty,VetsDisabilty,NonVetsPoor,VetsPoor,UnempRate2018,NumUnemployed2018,NumEmployed2018,NumCivLaborforce2018,PctEmpAgriculture,PctEmpMining,PctEmpConstruction,PctEmpManufacturing,PctEmpTrade,PctEmpTrans,PctEmpInformation,PctEmpFIRE,PctEmpServices,PctEmpGovt,RuralUrbanContinuumCode2013,UrbanInfluenceCode2013,Metro2013,Micropolitan2013,Type_2015_Farming_NO,Type_2015_Manufacturing_NO,Type_2015_Mining_NO,Type_2015_Government_NO,Type_2015_Recreation_NO,Low_Employment_2015_update,Population_loss_2015_update,Retirement_Destination_2015_Update,HiAmenity,Metro_Adjacent2013,num_hospitals,population,num_covid_cases,infection_pct,FIPS,num_nursing_homes,total_tests
0,23111.241421,anderson,45969.0,4.287712,2486.0,8778.0,1062.60,58057.0,55.01,7338,11475,-495.0,2.69,16459,11674,2001,16459,592,2046,8351,15224,10696,2807,4931,35792,12222,283,192,9287,993,TX,34618.0,21739.0,4012.0,2307.0,3018.0,253.0,3219.0,237.0,3.1,728.0,22833.0,23561.0,1.905654,6.919713,5.435801,6.175154,20.425909,6.638550,0.494637,3.097990,39.529314,9.377278,7.0,8.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,58199,1003,1.723397,48001,5.0,2679
1,5015.975463,andrews,84946.0,3.720851,774.0,1922.0,1500.71,18128.0,9.85,1663,4312,1408.0,3.22,5508,4024,545,5508,536,456,2695,3898,2161,753,1103,7083,199,85,95,7195,292,TX,49625.0,32142.0,685.0,478.0,797.0,28.0,891.0,0.0,2.4,225.0,9157.0,9382.0,1.277217,25.118599,7.772777,5.400803,12.236954,9.147306,1.423185,5.339983,30.312614,1.970563,6.0,5.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,22269,33,0.148188,48003,1.0,72
2,20927.331551,angelina,46653.0,7.613627,5855.0,15052.0,797.78,87092.0,108.77,11843,23206,2539.0,2.75,30783,20440,4777,30783,955,3463,10826,18265,14230,4578,9344,54889,12840,744,255,17145,1524,TX,31119.0,23093.0,5929.0,3077.0,7252.0,780.0,8112.0,478.0,4.4,1589.0,34622.0,36211.0,2.012354,1.953660,6.836412,11.724755,15.592946,4.309791,0.531038,4.206378,48.601135,4.231532,5.0,8.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,90437,352,0.389221,48005,8.0,3002
3,8865.511478,aransas,46912.0,9.002793,1423.0,4642.0,252.07,23792.0,91.87,5602,4523,-760.0,2.58,9432,7344,697,9432,252,1521,2742,5392,4764,1302,3936,16350,258,443,118,5690,523,TX,31986.0,21220.0,2584.0,1102.0,1767.0,326.0,2775.0,207.0,5.7,589.0,9725.0,10314.0,1.157430,3.540951,12.359000,4.963217,13.859735,3.089750,0.519863,4.717999,49.759686,6.032369,2.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,27699,7,0.025272,48007,2.0,317
4,2147.672378,archer,61190.0,3.490241,268.0,922.0,903.11,8786.0,10.03,1447,2185,-39.0,2.61,3332,2804,250,3332,70,429,558,2057,1655,462,1449,8182,34,18,47,675,134,TX,40500.0,30941.0,625.0,326.0,563.0,44.0,383.0,8.0,3.1,129.0,4055.0,4184.0,5.336374,4.424173,7.366021,7.708096,15.963512,4.811859,0.957811,5.267959,42.850627,5.313569,3.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8344,3,0.035954,48009,1.0,79

In [22]:
def replace_nulls_in_df(df):
    """
    Takes in the dataframe and replaces the nulls with 0
    """
    return df.fillna(0)

In [23]:
df = yk_acquire.merge_dataframes()

In [24]:
df = replace_nulls_in_df(df)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 254 entries, 0 to 253
Data columns (total 74 columns):
LACCESS_POP15                         254 non-null float64
County                                254 non-null object
MedHHInc                              254 non-null float64
Deep_Pov_All                          254 non-null float64
PovertyUnder18Num                     254 non-null float64
PovertyAllAgesNum                     254 non-null float64
LandAreaSQMiles2010                   254 non-null float64
TotalPopEst2018                       254 non-null float64
PopDensity2010                        254 non-null float64
Age65AndOlderNum2010                  254 non-null int64
Under18Num2010                        254 non-null int64
NaturalChange1018                     254 non-null float64
AvgHHSize                             254 non-null float64
TotalOccHU                            254 non-null int64
OwnHomeNum                            254 non-null int64
FemaleHHNum                           254 non-null int64
TotalHH                               254 non-null int64
NonEnglishHHNum                       254 non-null int64
HH65PlusAloneNum                      254 non-null int64
Ed1LessThanHSNum                      254 non-null int64
Ed2HSDiplomaOnlyNum                   254 non-null int64
Ed3SomeCollegeNum                     254 non-null int64
Ed4AssocDegreeNum                     254 non-null int64
Ed5CollegePlusNum                     254 non-null int64
WhiteNonHispanicNum2010               254 non-null int64
BlackNonHispanicNum2010               254 non-null int64
AsianNonHispanicNum2010               254 non-null int64
NativeAmericanNonHispanicNum2010      254 non-null int64
HispanicNum2010                       254 non-null int64
MultipleRaceNum2010                   254 non-null int64
State                                 254 non-null object
MedianVetsInc                         254 non-null float64
MedianNonVetsInc                      254 non-null float64
Vets18ONum                            254 non-null float64
CLFVets18to64Num                      254 non-null float64
NonVetsDisabilty                      254 non-null float64
VetsDisabilty                         254 non-null float64
NonVetsPoor                           254 non-null float64
VetsPoor                              254 non-null float64
UnempRate2018                         254 non-null float64
NumUnemployed2018                     254 non-null float64
NumEmployed2018                       254 non-null float64
NumCivLaborforce2018                  254 non-null float64
PctEmpAgriculture                     254 non-null float64
PctEmpMining                          254 non-null float64
PctEmpConstruction                    254 non-null float64
PctEmpManufacturing                   254 non-null float64
PctEmpTrade                           254 non-null float64
PctEmpTrans                           254 non-null float64
PctEmpInformation                     254 non-null float64
PctEmpFIRE                            254 non-null float64
PctEmpServices                        254 non-null float64
PctEmpGovt                            254 non-null float64
RuralUrbanContinuumCode2013           254 non-null float64
UrbanInfluenceCode2013                254 non-null float64
Metro2013                             254 non-null float64
Micropolitan2013                      254 non-null float64
Type_2015_Farming_NO                  254 non-null float64
Type_2015_Manufacturing_NO            254 non-null float64
Type_2015_Mining_NO                   254 non-null float64
Type_2015_Government_NO               254 non-null float64
Type_2015_Recreation_NO               254 non-null float64
Low_Employment_2015_update            254 non-null float64
Population_loss_2015_update           254 non-null float64
Retirement_Destination_2015_Update    254 non-null float64
HiAmenity                             254 non-null float64
Metro_Adjacent2013                    254 non-null float64
num_hospitals                         254 non-null float64
population                            254 non-null int64
num_covid_cases                       254 non-null int64
infection_pct                         254 non-null float64
FIPS                                  254 non-null int64
num_nursing_homes                     254 non-null float64
total_tests                           254 non-null int64
dtypes: float64(49), int64(23), object(2)
memory usage: 148.8+ KB

In [28]:
df = pd.read_csv("mother_frame.csv")

In [29]:
df.head()

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,Under18Num2010,NaturalChange1018,AvgHHSize,TotalOccHU,OwnHomeNum,FemaleHHNum,TotalHH,NonEnglishHHNum,HH65PlusAloneNum,Ed1LessThanHSNum,Ed2HSDiplomaOnlyNum,Ed3SomeCollegeNum,Ed4AssocDegreeNum,Ed5CollegePlusNum,WhiteNonHispanicNum2010,BlackNonHispanicNum2010,AsianNonHispanicNum2010,NativeAmericanNonHispanicNum2010,HispanicNum2010,MultipleRaceNum2010,State,MedianVetsInc,MedianNonVetsInc,Vets18ONum,CLFVets18to64Num,NonVetsDisabilty,VetsDisabilty,NonVetsPoor,VetsPoor,UnempRate2018,NumUnemployed2018,NumEmployed2018,NumCivLaborforce2018,PctEmpAgriculture,PctEmpMining,PctEmpConstruction,PctEmpManufacturing,PctEmpTrade,PctEmpTrans,PctEmpInformation,PctEmpFIRE,PctEmpServices,PctEmpGovt,RuralUrbanContinuumCode2013,UrbanInfluenceCode2013,Metro2013,Micropolitan2013,Type_2015_Farming_NO,Type_2015_Manufacturing_NO,Type_2015_Mining_NO,Type_2015_Government_NO,Type_2015_Recreation_NO,Low_Employment_2015_update,Population_loss_2015_update,Retirement_Destination_2015_Update,HiAmenity,Metro_Adjacent2013,num_hospitals,population,num_covid_cases,infection_pct,FIPS,num_nursing_homes,total_tests,cases_per_1k,cases_per_10k,cases_per_100k,positivity_rate,pop_density,low_food_access_pct,pov_under_18_pct,pov_pct,senior_pct,children_pct,home_owner_pct,renter_pct,female_hh_pct,senior_hh_pct,non_english_hh_pct,Ed1_pct,Ed2_pct,Ed3_pct,Ed4_pct,Ed5_pct,white_pct,black_pct,asian_pct,nat_am_pct,hispanic_pct,multi_race_pct,med_inc_vet_vs_civ,all_vet_pct,disabled_pct,poor_vets_pct,pop_density_category,infection_pct_category
0,23111.241421,Anderson,45969,4.287712,2486,8778,1062,58057,55.01,7338,11475,-495,2.69,16459,11674,2001,16459,592,2046,8351,15224,10696,2807,4931,35792,12222,283,192,9287,993,TX,34618,21739,4012,2307,3018,253,3219,237,3.1,728.0,22833.0,23561,1.905654,6.919713,5.435801,6.175154,20.425909,6.638550,0.494637,3.097990,39.529314,9.377278,7,8,0,1,0,0,0,1,0,1,0,0,0,0,2,58199,1003,1.723397,48001,5,2679,17.23,172.34,1723.40,0.37,54.77,0.40,0.22,0.15,0.13,0.20,0.71,0.29,0.12,0.12,0.04,0.18,0.33,22.89,0.06,0.11,0.61,0.21,0.00,0.00,0.16,0.02,1.59,0.09,0.07,0.06,mid,high
1,5015.975463,Andrews,84946,3.720851,774,1922,1500,18128,9.85,1663,4312,1408,3.22,5508,4024,545,5508,536,456,2695,3898,2161,753,1103,7083,199,85,95,7195,292,TX,49625,32142,685,478,797,28,891,0,2.4,225.0,9157.0,9382,1.277217,25.118599,7.772777,5.400803,12.236954,9.147306,1.423185,5.339983,30.312614,1.970563,6,5,0,1,0,0,1,0,0,0,0,0,0,1,1,22269,33,0.148188,48003,1,72,1.48,14.82,148.19,0.46,14.84,0.23,0.18,0.09,0.07,0.19,0.73,0.27,0.10,0.08,0.10,0.15,0.22,12.03,0.04,0.06,0.32,0.01,0.00,0.00,0.32,0.01,1.54,0.04,0.05,0.00,mid,mid
2,20927.331551,Angelina,46653,7.613627,5855,15052,797,87092,108.77,11843,23206,2539,2.75,30783,20440,4777,30783,955,3463,10826,18265,14230,4578,9344,54889,12840,744,255,17145,1524,TX,31119,23093,5929,3077,7252,780,8112,478,4.4,1589.0,34622.0,36211,2.012354,1.953660,6.836412,11.724755,15.592946,4.309791,0.531038,4.206378,48.601135,4.231532,5,8,0,1,0,0,0,0,0,0,0,0,1,0,4,90437,352,0.389221,48005,8,3002,3.89,38.92,389.22,0.12,113.36,0.23,0.25,0.17,0.13,0.26,0.66,0.34,0.16,0.11,0.03,0.16,0.27,21.17,0.07,0.14,0.61,0.14,0.01,0.00,0.19,0.02,1.35,0.09,0.12,0.08,high,high
3,8865.511478,Aransas,46912,9.002793,1423,4642,252,23792,91.87,5602,4523,-760,2.58,9432,7344,697,9432,252,1521,2742,5392,4764,1302,3936,16350,258,443,118,5690,523,TX,31986,21220,2584,1102,1767,326,2775,207,5.7,589.0,9725.0,10314,1.157430,3.540951,12.359000,4.963217,13.859735,3.089750,0.519863,4.717999,49.759686,6.032369,2,2,1,0,0,0,0,0,1,1,0,1,1,0,0,27699,7,0.025272,48007,2,317,0.25,2.53,25.27,0.02,109.89,0.32,0.31,0.17,0.20,0.16,0.78,0.22,0.07,0.16,0.03,0.12,0.23,20.56,0.06,0.17,0.59,0.01,0.02,0.00,0.21,0.02,1.51,0.11,0.09,0.08,high,low
4,2147.672378,Archer,61190,3.490241,268,922,903,8786,10.03,1447,2185,-39,2.61,3332,2804,250,3332,70,429,558,2057,1655,462,1449,8182,34,18,47,675,134,TX,40500,30941,625,326,563,44,383,8,3.1,129.0,4055.0,4184,5.336374,4.424173,7.366021,7.708096,15.963512,4.811859,0.957811,5.267959,42.850627,5.313569,3,2,1,0,0,0,1,0,0,0,0,0,0,0,0,8344,3,0.035954,48009,1,79,0.36,3.60,35.95,0.04,9.24,0.26,0.12,0.11,0.17,0.26,0.84,0.16,0.08,0.13,0.02,0.09,0.33,26.87,0.08,0.24,0.98,0.00,0.00,0.01,0.08,0.02,1.31,0.10,0.10,0.01,mid,low

In [31]:
df.columns.to_list()

['LACCESS_POP15',
 'County',
 'MedHHInc',
 'Deep_Pov_All',
 'PovertyUnder18Num',
 'PovertyAllAgesNum',
 'LandAreaSQMiles2010',
 'TotalPopEst2018',
 'PopDensity2010',
 'Age65AndOlderNum2010',
 'Under18Num2010',
 'NaturalChange1018',
 'AvgHHSize',
 'TotalOccHU',
 'OwnHomeNum',
 'FemaleHHNum',
 'TotalHH',
 'NonEnglishHHNum',
 'HH65PlusAloneNum',
 'Ed1LessThanHSNum',
 'Ed2HSDiplomaOnlyNum',
 'Ed3SomeCollegeNum',
 'Ed4AssocDegreeNum',
 'Ed5CollegePlusNum',
 'WhiteNonHispanicNum2010',
 'BlackNonHispanicNum2010',
 'AsianNonHispanicNum2010',
 'NativeAmericanNonHispanicNum2010',
 'HispanicNum2010',
 'MultipleRaceNum2010',
 'State',
 'MedianVetsInc',
 'MedianNonVetsInc',
 'Vets18ONum',
 'CLFVets18to64Num',
 'NonVetsDisabilty',
 'VetsDisabilty',
 'NonVetsPoor',
 'VetsPoor',
 'UnempRate2018',
 'NumUnemployed2018',
 'NumEmployed2018',
 'NumCivLaborforce2018',
 'PctEmpAgriculture',
 'PctEmpMining',
 'PctEmpConstruction',
 'PctEmpManufacturing',
 'PctEmpTrade',
 'PctEmpTrans',
 'PctEmpInformation',
 'PctEmpFIRE',
 'PctEmpServices',
 'PctEmpGovt',
 'RuralUrbanContinuumCode2013',
 'UrbanInfluenceCode2013',
 'Metro2013',
 'Micropolitan2013',
 'Type_2015_Farming_NO',
 'Type_2015_Manufacturing_NO',
 'Type_2015_Mining_NO',
 'Type_2015_Government_NO',
 'Type_2015_Recreation_NO',
 'Low_Employment_2015_update',
 'Population_loss_2015_update',
 'Retirement_Destination_2015_Update',
 'HiAmenity',
 'Metro_Adjacent2013',
 'num_hospitals',
 'population',
 'num_covid_cases',
 'infection_pct',
 'FIPS',
 'num_nursing_homes',
 'total_tests',
 'cases_per_1k',
 'cases_per_10k',
 'cases_per_100k',
 'positivity_rate',
 'pop_density',
 'low_food_access_pct',
 'pov_under_18_pct',
 'pov_pct',
 'senior_pct',
 'children_pct',
 'home_owner_pct',
 'renter_pct',
 'female_hh_pct',
 'senior_hh_pct',
 'non_english_hh_pct',
 'Ed1_pct',
 'Ed2_pct',
 'Ed3_pct',
 'Ed4_pct',
 'Ed5_pct',
 'white_pct',
 'black_pct',
 'asian_pct',
 'nat_am_pct',
 'hispanic_pct',
 'multi_race_pct',
 'med_inc_vet_vs_civ',
 'all_vet_pct',
 'disabled_pct',
 'poor_vets_pct',
 'pop_density_category',
 'infection_pct_category']

In [32]:
tx_svi = pd.read_csv("../data/Texas_COUNTY.csv")

In [34]:
tx_svi.columns.to_list()

['ST',
 'STATE',
 'ST_ABBR',
 'COUNTY',
 'FIPS',
 'LOCATION',
 'AREA_SQMI',
 'E_TOTPOP',
 'M_TOTPOP',
 'E_HU',
 'M_HU',
 'E_HH',
 'M_HH',
 'E_POV',
 'M_POV',
 'E_UNEMP',
 'M_UNEMP',
 'E_PCI',
 'M_PCI',
 'E_NOHSDP',
 'M_NOHSDP',
 'E_AGE65',
 'M_AGE65',
 'E_AGE17',
 'M_AGE17',
 'E_DISABL',
 'M_DISABL',
 'E_SNGPNT',
 'M_SNGPNT',
 'E_MINRTY',
 'M_MINRTY',
 'E_LIMENG',
 'M_LIMENG',
 'E_MUNIT',
 'M_MUNIT',
 'E_MOBILE',
 'M_MOBILE',
 'E_CROWD',
 'M_CROWD',
 'E_NOVEH',
 'M_NOVEH',
 'E_GROUPQ',
 'M_GROUPQ',
 'EP_POV',
 'MP_POV',
 'EP_UNEMP',
 'MP_UNEMP',
 'EP_PCI',
 'MP_PCI',
 'EP_NOHSDP',
 'MP_NOHSDP',
 'EP_AGE65',
 'MP_AGE65',
 'EP_AGE17',
 'MP_AGE17',
 'EP_DISABL',
 'MP_DISABL',
 'EP_SNGPNT',
 'MP_SNGPNT',
 'EP_MINRTY',
 'MP_MINRTY',
 'EP_LIMENG',
 'MP_LIMENG',
 'EP_MUNIT',
 'MP_MUNIT',
 'EP_MOBILE',
 'MP_MOBILE',
 'EP_CROWD',
 'MP_CROWD',
 'EP_NOVEH',
 'MP_NOVEH',
 'EP_GROUPQ',
 'MP_GROUPQ',
 'EPL_POV',
 'EPL_UNEMP',
 'EPL_PCI',
 'EPL_NOHSDP',
 'SPL_THEME1',
 'RPL_THEME1',
 'EPL_AGE65',
 'EPL_AGE17',
 'EPL_DISABL',
 'EPL_SNGPNT',
 'SPL_THEME2',
 'RPL_THEME2',
 'EPL_MINRTY',
 'EPL_LIMENG',
 'SPL_THEME3',
 'RPL_THEME3',
 'EPL_MUNIT',
 'EPL_MOBILE',
 'EPL_CROWD',
 'EPL_NOVEH',
 'EPL_GROUPQ',
 'SPL_THEME4',
 'RPL_THEME4',
 'SPL_THEMES',
 'RPL_THEMES',
 'F_POV',
 'F_UNEMP',
 'F_PCI',
 'F_NOHSDP',
 'F_THEME1',
 'F_AGE65',
 'F_AGE17',
 'F_DISABL',
 'F_SNGPNT',
 'F_THEME2',
 'F_MINRTY',
 'F_LIMENG',
 'F_THEME3',
 'F_MUNIT',
 'F_MOBILE',
 'F_CROWD',
 'F_NOVEH',
 'F_GROUPQ',
 'F_THEME4',
 'F_TOTAL',
 'E_UNINSUR',
 'M_UNINSUR',
 'EP_UNINSUR',
 'MP_UNINSUR',
 'E_DAYPOP']

The four summary theme ranking variables, detailed in the Data Dictionary below, are:
- Socioeconomic - RPL_THEME1
- Household Composition & Disability - RPL_THEME2
- Minority Status & Language - RPL_THEME3
- Housing Type & Transportation - RPL_THEME4

The overall tract summary ranking variable is RPL_THEMES.

In [35]:
col_to_keep = ['FIPS',
              'RPL_THEME1',
              'RPL_THEME2',
              'RPL_THEME3',
              'RPL_THEME4',
              'RPL_THEMES']

In [36]:
tx_svi = tx_svi[col_to_keep]

In [37]:
tx_svi

      FIPS  RPL_THEME1  RPL_THEME2  RPL_THEME3  RPL_THEME4  RPL_THEMES
0    48065      0.0040      0.2964      0.0198      0.0198      0.0000
1    48009      0.0474      0.1937      0.0277      0.0079      0.0040
2    48397      0.0277      0.0514      0.2490      0.0553      0.0079
3    48011      0.0119      0.1146      0.0356      0.1146      0.0119
4    48033      0.0000      0.8735      0.0000      0.0040      0.0158
..     ...         ...         ...         ...         ...         ...
249  48505      0.9921      0.9565      0.9881      0.8577      0.9842
250  48131      0.9644      0.9842      0.8656      0.8735      0.9881
251  48047      0.9802      0.9447      0.9486      0.9684      0.9921
252  48507      0.9763      0.9763      0.9328      0.9407      0.9960
253  48127      0.9684      0.9881      0.9012      0.9526      1.0000

[254 rows x 6 columns]

In [39]:
tx_svi.isnull().sum()

FIPS          0
RPL_THEME1    0
RPL_THEME2    0
RPL_THEME3    0
RPL_THEME4    0
RPL_THEMES    0
dtype: int64

In [42]:
tx_svi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 6 columns):
FIPS          254 non-null int64
RPL_THEME1    254 non-null float64
RPL_THEME2    254 non-null float64
RPL_THEME3    254 non-null float64
RPL_THEME4    254 non-null float64
RPL_THEMES    254 non-null float64
dtypes: float64(5), int64(1)
memory usage: 12.0 KB

In [43]:
def acquire_cdc_svi_index():
    """
    Acquires the Texas counties csv from the CDC fir info
    on the Social Vilnerability Index (SVI) and prepares the dataframe to merge
    onto the main dataframe
    """
    #read in the dataframe
    tx_svi = pd.read_csv("../data/Texas_COUNTY.csv")
    
    #columns to keep
    col_to_keep = ['FIPS',
              'RPL_THEME1',
              'RPL_THEME2',
              'RPL_THEME3',
              'RPL_THEME4',
              'RPL_THEMES']
    
    #drop columns that are not needed
    tx_svi = tx_svi[col_to_keep]
    
    return tx_svi

In [44]:
acquire_cdc_svi_index()

      FIPS  RPL_THEME1  RPL_THEME2  RPL_THEME3  RPL_THEME4  RPL_THEMES
0    48065      0.0040      0.2964      0.0198      0.0198      0.0000
1    48009      0.0474      0.1937      0.0277      0.0079      0.0040
2    48397      0.0277      0.0514      0.2490      0.0553      0.0079
3    48011      0.0119      0.1146      0.0356      0.1146      0.0119
4    48033      0.0000      0.8735      0.0000      0.0040      0.0158
..     ...         ...         ...         ...         ...         ...
249  48505      0.9921      0.9565      0.9881      0.8577      0.9842
250  48131      0.9644      0.9842      0.8656      0.8735      0.9881
251  48047      0.9802      0.9447      0.9486      0.9684      0.9921
252  48507      0.9763      0.9763      0.9328      0.9407      0.9960
253  48127      0.9684      0.9881      0.9012      0.9526      1.0000

[254 rows x 6 columns]

In [45]:
df.sample()

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,Under18Num2010,NaturalChange1018,AvgHHSize,TotalOccHU,OwnHomeNum,FemaleHHNum,TotalHH,NonEnglishHHNum,HH65PlusAloneNum,Ed1LessThanHSNum,Ed2HSDiplomaOnlyNum,Ed3SomeCollegeNum,Ed4AssocDegreeNum,Ed5CollegePlusNum,WhiteNonHispanicNum2010,BlackNonHispanicNum2010,AsianNonHispanicNum2010,NativeAmericanNonHispanicNum2010,HispanicNum2010,MultipleRaceNum2010,State,MedianVetsInc,MedianNonVetsInc,Vets18ONum,CLFVets18to64Num,NonVetsDisabilty,VetsDisabilty,NonVetsPoor,VetsPoor,UnempRate2018,NumUnemployed2018,NumEmployed2018,NumCivLaborforce2018,PctEmpAgriculture,PctEmpMining,PctEmpConstruction,PctEmpManufacturing,PctEmpTrade,PctEmpTrans,PctEmpInformation,PctEmpFIRE,PctEmpServices,PctEmpGovt,RuralUrbanContinuumCode2013,UrbanInfluenceCode2013,Metro2013,Micropolitan2013,Type_2015_Farming_NO,Type_2015_Manufacturing_NO,Type_2015_Mining_NO,Type_2015_Government_NO,Type_2015_Recreation_NO,Low_Employment_2015_update,Population_loss_2015_update,Retirement_Destination_2015_Update,HiAmenity,Metro_Adjacent2013,num_hospitals,population,num_covid_cases,infection_pct,FIPS,num_nursing_homes,total_tests,cases_per_1k,cases_per_10k,cases_per_100k,positivity_rate,pop_density,low_food_access_pct,pov_under_18_pct,pov_pct,senior_pct,children_pct,home_owner_pct,renter_pct,female_hh_pct,senior_hh_pct,non_english_hh_pct,Ed1_pct,Ed2_pct,Ed3_pct,Ed4_pct,Ed5_pct,white_pct,black_pct,asian_pct,nat_am_pct,hispanic_pct,multi_race_pct,med_inc_vet_vs_civ,all_vet_pct,disabled_pct,poor_vets_pct,pop_density_category,infection_pct_category
197,5362.69054,Robertson,44917,4.669984,1052,2699,855,17284,19.43,2770,4213,204,2.63,6358,4805,913,6358,246,737,1843,4179,3027,513,1839,9821,3509,96,47,2990,327,TX,32292,24126,922,367,1183,75,1173,34,4.1,317.0,7338.0,7655,7.620592,2.877989,8.944737,10.322929,14.362924,8.228618,1.526821,1.270099,40.99446,3.850831,3,2,1,0,0,0,1,0,0,0,0,0,0,0,0,16888,23,0.136191,48395,3,473,1.36,13.62,136.19,0.05,19.74,0.32,0.25,0.16,0.16,0.25,0.76,0.24,0.14,0.12,0.04,0.15,0.33,23.88,0.04,0.15,0.58,0.21,0.01,0.0,0.18,0.02,1.34,0.07,0.1,0.04,mid,mid

In [46]:
df1 = df.join(tx_svi.set_index("FIPS"), on="FIPS")

In [47]:
df1

,LACCESS_POP15,County,MedHHInc,Deep_Pov_All,PovertyUnder18Num,PovertyAllAgesNum,LandAreaSQMiles2010,TotalPopEst2018,PopDensity2010,Age65AndOlderNum2010,Under18Num2010,NaturalChange1018,AvgHHSize,TotalOccHU,OwnHomeNum,FemaleHHNum,TotalHH,NonEnglishHHNum,HH65PlusAloneNum,Ed1LessThanHSNum,Ed2HSDiplomaOnlyNum,Ed3SomeCollegeNum,Ed4AssocDegreeNum,Ed5CollegePlusNum,WhiteNonHispanicNum2010,BlackNonHispanicNum2010,AsianNonHispanicNum2010,NativeAmericanNonHispanicNum2010,HispanicNum2010,MultipleRaceNum2010,State,MedianVetsInc,MedianNonVetsInc,Vets18ONum,CLFVets18to64Num,NonVetsDisabilty,VetsDisabilty,NonVetsPoor,VetsPoor,UnempRate2018,NumUnemployed2018,NumEmployed2018,NumCivLaborforce2018,PctEmpAgriculture,PctEmpMining,PctEmpConstruction,PctEmpManufacturing,PctEmpTrade,PctEmpTrans,PctEmpInformation,PctEmpFIRE,PctEmpServices,PctEmpGovt,RuralUrbanContinuumCode2013,UrbanInfluenceCode2013,Metro2013,Micropolitan2013,Type_2015_Farming_NO,Type_2015_Manufacturing_NO,Type_2015_Mining_NO,Type_2015_Government_NO,Type_2015_Recreation_NO,Low_Employment_2015_update,Population_loss_2015_update,Retirement_Destination_2015_Update,HiAmenity,Metro_Adjacent2013,num_hospitals,population,num_covid_cases,infection_pct,FIPS,num_nursing_homes,total_tests,cases_per_1k,cases_per_10k,cases_per_100k,positivity_rate,pop_density,low_food_access_pct,pov_under_18_pct,pov_pct,senior_pct,children_pct,home_owner_pct,renter_pct,female_hh_pct,senior_hh_pct,non_english_hh_pct,Ed1_pct,Ed2_pct,Ed3_pct,Ed4_pct,Ed5_pct,white_pct,black_pct,asian_pct,nat_am_pct,hispanic_pct,multi_race_pct,med_inc_vet_vs_civ,all_vet_pct,disabled_pct,poor_vets_pct,pop_density_category,infection_pct_category,RPL_THEME1,RPL_THEME2,RPL_THEME3,RPL_THEME4,RPL_THEMES
0,23111.241421,Anderson,45969,4.287712,2486,8778,1062,58057,55.01,7338,11475,-495,2.69,16459,11674,2001,16459,592,2046,8351,15224,10696,2807,4931,35792,12222,283,192,9287,993,TX,34618,21739,4012,2307,3018,253,3219,237,3.1,728.0,22833.0,23561,1.905654,6.919713,5.435801,6.175154,20.425909,6.638550,0.494637,3.097990,39.529314,9.377278,7,8,0,1,0,0,0,1,0,1,0,0,0,0,2,58199,1003,1.723397,48001,5,2679,17.23,172.34,1723.40,0.37,54.77,0.40,0.22,0.15,0.13,0.20,0.71,0.29,0.12,0.12,0.04,0.18,0.33,22.89,0.06,0.11,0.61,0.21,0.00,0.00,0.16,0.02,1.59,0.09,0.07,0.06,mid,high,0.6166,0.0751,0.4150,0.9486,0.6206
1,5015.975463,Andrews,84946,3.720851,774,1922,1500,18128,9.85,1663,4312,1408,3.22,5508,4024,545,5508,536,456,2695,3898,2161,753,1103,7083,199,85,95,7195,292,TX,49625,32142,685,478,797,28,891,0,2.4,225.0,9157.0,9382,1.277217,25.118599,7.772777,5.400803,12.236954,9.147306,1.423185,5.339983,30.312614,1.970563,6,5,0,1,0,0,1,0,0,0,0,0,0,1,1,22269,33,0.148188,48003,1,72,1.48,14.82,148.19,0.46,14.84,0.23,0.18,0.09,0.07,0.19,0.73,0.27,0.10,0.08,0.10,0.15,0.22,12.03,0.04,0.06,0.32,0.01,0.00,0.00,0.32,0.01,1.54,0.04,0.05,0.00,mid,mid,0.2964,0.0593,0.8261,0.4822,0.3794
2,20927.331551,Angelina,46653,7.613627,5855,15052,797,87092,108.77,11843,23206,2539,2.75,30783,20440,4777,30783,955,3463,10826,18265,14230,4578,9344,54889,12840,744,255,17145,1524,TX,31119,23093,5929,3077,7252,780,8112,478,4.4,1589.0,34622.0,36211,2.012354,1.953660,6.836412,11.724755,15.592946,4.309791,0.531038,4.206378,48.601135,4.231532,5,8,0,1,0,0,0,0,0,0,0,0,1,0,4,90437,352,0.389221,48005,8,3002,3.89,38.92,389.22,0.12,113.36,0.23,0.25,0.17,0.13,0.26,0.66,0.34,0.16,0.11,0.03,0.16,0.27,21.17,0.07,0.14,0.61,0.14,0.01,0.00,0.19,0.02,1.35,0.09,0.12,0.08,high,high,0.8221,0.9209,0.5534,0.9170,0.9051
3,8865.511478,Aransas,46912,9.002793,1423,4642,252,23792,91.87,5602,4523,-760,2.58,9432,7344,697,9432,252,1521,2742,5392,4764,1302,3936,16350,258,443,118,5690,523,TX,31986,21220,2584,1102,1767,326,2775,207,5.7,589.0,9725.0,10314,1.157430,3.540951,12.359000,4.963217,13.859735,3.089750,0.519863,4.717999,49.759686,6.032369,2,2,1,0,0,0,0,0,1,1,0,1,1,0,0,27699,7,0.025272,48007,2,317,0.25,2.53,25.27,0.02,109.89,0.32,0.31,0.17,0.20,0.16,0.78,0.22,0.07,0.16,0.03,0.12,0.23,20.56,0.06,0.17,0.59,0.01,0.02,0.00,0.21,0.02,1.51,0.11,0.09,0.08,high,low,0.5178,0.5534,0.3281,0.7945,0.5968
4,2147.672378,Archer,61190,3.490241,268,922,903,8786,10.03,1447,2185,-39,2.61,3332,2804,250,3332,70,429,558,2057,1655,462,1449,8182,34,18,47,675,134,TX,40500,30941,625,326,563,44,383,8,3.1,129.0,4055.0,4184,5.336374,4.424173,7.366021,7.708096,15.963512,4.811859,0.957811,5.267959,42.850627,5.313569,3,2,1,0,0,0,1,0,0,0,0,0,0,0,0,8344,3,0.035954,48009,1,79,0.36,3.60,35.95,0.04,9.24,0.26,0.12,0.11,0.17,0.26,0.84,0.16,0.08,0.13,0.02,0.09,0.33,26.87,0.08,0.24,0.98,0.00,0.00,0.01,0.08,0.02,1.31,0.10,0.10,0.01,mid,low,0.0474,0.1937,0.0277,0.0079,0.0040
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,3222.188853,Wood,48384,6.128292,2116,6625,645,45129,65.04,10148,8528,-1611,2.56,16531,13221,1676,16531,282,2379,4852,10919,8727,2203,5246,35628,1951,156,198,3551,593,TX,31886,23770,4175,1304,3693,453,2992,177,4.2,736.0,16607.0,17343,2.172818,2.638871,7.922912,9.774531,17.099131,6.486963,2.437335,5.353319,40.042827,6.071294,6,6,0,0,0,0,0,0,0,1,0,1,1,1,2,45292,66,0.145721,48499,5,769,1.46,14.57,145.72,0.09,70.20,0.07,0.25,0.15,0.22,0.19,0.80,0.20,0.10,0.14,0.02,0.13,0.30,23.74,0.06,0.14,0.79,0.04,0.00,0.00,0.08,0.01,1.34,0.11,0.11,0.04,high,mid,0.3478,0.7628,0.0870,0.2648,0.2490
250,1562.352965,Yoakum,61560,5.705285,454,1028,799,8591,9.85,895,2501,758,3.20,2676,2121,169,2676,475,212,1595,1445,800,353,817,3090,55,26,30,4622,210,TX,49345,33180,195,58,214,23,317,4,2.8,106.0,3630.0,3736,8.293461,23.258905,7.575758,1.382243,8.878256,12.679426,2.232855,1.329080,30.462520,3.907496,7,9,0,0,0,0,1,0,0,0,0,0,0,0,1,9225,11,0.119241,48501,1,183,1.19,11.92,119.24,0.06,11.54,0.17,0.18,0.11,0.10,0.27,0.79,0.21,0.06,0.08,0.18,0.24,0.21,11.90,0.05,0.12,0.33,0.01,0.00,0.00,0.50,0.02,1.49,0.03,0.04,0.02,mid,mid,0.4941,0.0514,0.9328,0.3320,0.4545
251,6142.001383,Young,49301,5.501855,873,2468,914,18045,20.29,3422,4459,-238,2.51,7105,5547,763,7105,476,792,2019,4371,3142,471,2438,14959,220,55,83,3045,358,TX,31455,25957,1142,386,1158,72,1125,39,3.2,265.0,7922.0,8187,3.132380,9.720323,9.297700,12.827843,13.039155,4.176507,1.218148,2.784338,40.074580,3.729024,7,11,0,0,0,0,1,0,0,0,0,0,0,0,2,18712,15,0.080162,48503,3,708,0.80,8.02,80.16,0.02,20.46,0.33,0.20,0.13,0.18,0.24,0.78,0.22,0.11,0.11,0.07,0.14,0.31,22.04,0.03,0.17,0.80,0.01,0.00,0.00,0.16,0.02,1.21,0.08,0.09,0.03,mid,mid,0.1818,0.8024,0.1304,0.1739,0.1779
252,6065.681176,Zapata,33160,18.348365,2297,4529,998,14190,14.04,1460,4805,1504,3.25,4405,3103,942,4405,1419,369,3226,2378,1282,338,835,861,11,28,16,13084,78,TX,30911,15760,455,160,1221,8,2610,0,5.6,299.0,5077.0,5376,2.839555,13.840349,13.780778,2.561557,8.657665,3.435266,1.409849,2.124702,43.685465,7.664813,6,5,0,1,0,0,1,0,0,0,0,0,1,1,0,14409,31,0.215143,48505,1,421,2.15,21.51,215.14,0.07,14.43,0.42,0.48,0.31,0.10,0.33,0.70,0.30,0.21,0.08,0.32,0.34,0.25,13.35,0.04,0.09,0.06,0.00,0.00,0.00,0.91,0.01,1.96,0.05,0.13,0.00,mid,mid,0.9921,0.9565,0.9881,0.8577,0.9842
253,3702.027063,Zavala,30076,15.852535,1549,3701,1297,11983,9.00,1408,3660,772,3.40,3509,2478,923,3509,517,301,2719,2240,1181,395,614,647,35,3,9,10961,164,TX,28750,14174,369,164,1448,97,1466,0,9.5,343.0,3250.0,3593,6.206446,3.288328,5.923345,6.315331,11.215157,3.244774,0.936411,0.914634,57.491289,4.464286,7,9,0,0,0,0,0,0,0,1,0,0,0,0,0,12682,13,0.102507,48507,0,110,1.03,10.25,102.51,0.12,9.77,0.29,0.42,0.29,0.11,0.29,0.71,0.29,0.26,0.09,0.15,0.30,0.25,13.09,0.04,0.07,0.05,0.00,0.00,0.00,0.86,0.01,2.03,0.04,0.17,0.00,mid,mid,0.9763,0.9763,0.9328,0.9407,0.9960